# fly.toml app configuration file generated for gary-web on 2026-08-09T11:08:46Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'gary-web'
primary_region = 'ord'

[build]
  dockerfile = 'apps/gary-web/Dockerfile'

[env]
  GARY_API_URL = 'http://gary-api.internal:8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  size = 'shared-cpu-1x'
  memory = '512mb'
