version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly

  - package-ecosystem: npm
    directories:
      - /
      - /apps/example-web
    schedule:
      interval: weekly

  - package-ecosystem: uv
    directory: /apps/example-api
    schedule:
      interval: weekly
