import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

// One config for the whole workspace, at the root, because eslint will not
// lint a file outside its config's base path. Run from apps/gary-web this
// answered "File ignored because outside of base path" for every component in
// packages/ui — a warning, so `pnpm exec eslint` there exited 0 having linted
// none of them. Twenty-six files went unlinted that way.
//
// eslint and eslint-config-next are declared in the ROOT package.json for the
// same reason. They used to be gary-web's alone, and `pnpm exec eslint` from
// here found a global eslint on PATH instead — a different major, present on
// one machine and not in CI. A lint that passes because it ran the wrong
// binary is worse than no lint.

// Ours, and extended into both blocks below rather than left sitting at the
// top level on its own. A bare config object naming a rule from a plugin it
// does not itself register is a fatal eslint error — "could not find plugin
// @typescript-eslint" — and it is fatal at exit code 2, which is not the 1
// that means somebody wrote bad code. It has to travel with the config that
// brings the plugin in.
const ours = {
  rules: {
    // This codebase marks deliberately-unused arguments with a leading
    // underscore — useActionState dictates a signature whether or not the
    // action wants every part of it. Honour that rather than warn about it.
    "@typescript-eslint/no-unused-vars": [
      "warn",
      { argsIgnorePattern: "^_", varsIgnorePattern: "^_" },
    ],
  },
};

const config = defineConfig([
  {
    // Next's rules are about a Next app, so they apply to the one there is.
    // Pointing them at a component library would ask for a pages directory
    // that is not there and never will be.
    files: ["apps/gary-web/**/*.{js,jsx,mjs,ts,tsx}"],
    extends: [nextVitals, nextTs, ours],
    // Where the Next app actually is. Some of its rules go looking for the
    // app on disk rather than reading the file in front of them, and from
    // this config's directory they looked at the repo root and reported
    // "Pages directory cannot be found" on every run. That is the cost of
    // moving the config up, and it is one line.
    settings: { next: { rootDir: "apps/gary-web" } },
  },
  {
    // The library gets the TypeScript rules and not the app ones. These are
    // presentational components built from radix and cva — there is no
    // routing, no next/image, no server boundary for the Next rules to have
    // an opinion about.
    files: ["packages/ui/**/*.{ts,tsx}"],
    extends: [nextTs, ours],
  },
  globalIgnores([
    // Default ignores of eslint-config-next, which naming a config of our own
    // replaces rather than adds to.
    "**/.next/**",
    "**/out/**",
    "**/build/**",
    "**/next-env.d.ts",
    // Generated by the coverage reporter, not ours to lint.
    "**/coverage/**",
  ]),
]);

export default config;
