version: '3'

includes:
  gary-api:
    taskfile: ./apps/gary-api
    dir: ./apps/gary-api
  gary-web:
    taskfile: ./apps/gary-web
    dir: ./apps/gary-web
  ui:
    taskfile: ./packages/ui
    dir: ./packages/ui

tasks:
  test:
    desc: Run every app's tests
    cmds:
      - task: gary-api:test
      - task: ui:test
      - task: gary-web:test
