"""let a campaign name its model

Revision ID: 1ff531109c39
Revises: 2c14ff007429
Create Date: 2026-08-11 07:07:47.142833

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ff531109c39'
down_revision: Union[str, Sequence[str], None] = '2c14ff007429'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaigns', sa.Column('model', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('campaigns', 'model')
    # ### end Alembic commands ###
