"""'add character experience'

Revision ID: 66bd3563c80e
Revises: cef8c120eedf
Create Date: 2026-08-23 04:46:37.920593

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66bd3563c80e'
down_revision: Union[str, Sequence[str], None] = 'cef8c120eedf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema.

    Hand-finished. Zero is right for every character that already exists, and
    not by luck: nothing has ever been able to write this, so every one of
    them is level 1, and level 1 costs nothing in every system that prices a
    level at all.
    """
    # server_default, or a NOT NULL column cannot be added to a table that
    # already has rows. Kept afterwards rather than dropped: a character with
    # no experience is what a character is until something awards them some,
    # at the database as much as in the model.
    op.add_column(
        'characters',
        sa.Column(
            'experience',
            sa.Integer(),
            nullable=False,
            server_default='0',
        ),
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('characters', 'experience')
    # ### end Alembic commands ###
