"""'say who plays each character'

Revision ID: 9ce5b25ff4b3
Revises: 3e832954410d
Create Date: 2026-08-11 20:15:10.349607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ce5b25ff4b3'
down_revision: Union[str, Sequence[str], None] = '3e832954410d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema.

    Hand-finished. Autogenerate adds the column with its default and stops,
    which would make every existing character a companion — a campaign with a
    party but nobody in it you are, which is the one state the party step
    exists to make unreachable. So the character each campaign started with
    becomes the one you play, which is what they were before there was a
    distinction.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default, or a NOT NULL column cannot be added to a table that
    # already has rows. Kept afterwards rather than dropped: a companion is
    # what a character is unless somebody says otherwise, at the database as
    # much as in the model.
    op.add_column(
        'characters',
        sa.Column(
            'played_by',
            sa.String(length=8),
            nullable=False,
            server_default='gary',
        ),
    )
    op.execute(
        """
        UPDATE characters SET played_by = 'player'
        WHERE id IN (
            SELECT DISTINCT ON (campaign_id) id FROM characters
            ORDER BY campaign_id, created_at, name
        )
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('characters', 'played_by')
    # ### end Alembic commands ###
